port: 4444

title: "Jintao Lee"
#email: lijintaobt@gmail.com
description: "Personal blog of Jintao Lee"

#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com

search: true
paginate: 5
timezone: Asia/Shanghai

minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      # read_time: true
      # comments: true
      # share: true
      # related: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
